package com.myeongro.api.domain.saju.calculation;

public enum SajuLimitationCode {
	BIRTH_TIME_UNKNOWN,
	APPROXIMATE_BIRTH_TIME,
	YEAR_PILLAR_UNCERTAIN,
	MONTH_PILLAR_UNCERTAIN,
	DAY_PILLAR_UNCERTAIN,
	TIME_PILLAR_UNCERTAIN,
	LUCK_CYCLE_UNCERTAIN,
	LUCK_DIRECTION_UNSPECIFIED
}
