spring:
  config:
    activate:
      on-profile: prod

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        domain: ${session.cookie-domain}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
