output "aws_region" {
  description = "GitHub repo variable: AWS_REGION"
  value       = var.aws_region
}

output "ecr_repository" {
  description = "GitHub repo variable: ECR_REPOSITORY"
  value       = aws_ecr_repository.backend.name
}

output "aws_publish_role_arn" {
  description = "GitHub repo variable: AWS_PUBLISH_ROLE_ARN"
  value       = aws_iam_role.publish.arn
}

output "aws_deploy_role_arn" {
  description = "GitHub repo variable: AWS_DEPLOY_ROLE_ARN"
  value       = aws_iam_role.deploy.arn
}

output "github_oidc_provider_arn" {
  description = "Account-level GitHub OIDC provider ARN; pass this into non-production states"
  value       = local.github_oidc_provider_arn
}

output "ec2_instance_id" {
  description = "GitHub repo variable: EC2_INSTANCE_ID"
  value       = aws_instance.backend.id
}

output "ssm_backend_env_parameter" {
  description = "GitHub repo variable: SSM_BACKEND_ENV_PARAMETER"
  value       = aws_ssm_parameter.backend_env.name
}

output "api_domain_name" {
  description = "GitHub repo variable: API_DOMAIN_NAME"
  value       = var.api_domain_name
}

output "backend_public_ip" {
  description = "Create an A record for API_DOMAIN_NAME pointing to this Elastic IP"
  value       = aws_eip.backend.public_ip
}

output "cloudwatch_log_group" {
  description = "GitHub repo variable: CLOUDWATCH_LOG_GROUP"
  value       = aws_cloudwatch_log_group.backend.name
}

output "database_endpoint" {
  description = "RDS endpoint without the port"
  value       = aws_db_instance.postgres.address
}

output "database_name" {
  description = "Initial PostgreSQL database name"
  value       = aws_db_instance.postgres.db_name
}

output "database_master_secret_arn" {
  description = "Secrets Manager ARN generated by RDS for the bootstrap administrator"
  value       = aws_db_instance.postgres.master_user_secret[0].secret_arn
}

output "alarm_topic_arn" {
  description = "SNS topic receiving production alarms; null until alarm_notification_email is configured"
  value       = try(aws_sns_topic.production_alarms[0].arn, null)
}
