package com.myeongro.api.database;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class FlywayBaselineContractTests {

    private static final Path MIGRATION_DIRECTORY =
        Path.of("src", "main", "resources", "db", "migration");

    @Test
    void v1RecreatesTheCurrentSupabaseApplicationSchema() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V1__"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("create table public.profiles")
            .contains("create table public.readings")
            .contains("create table public.consents")
            .contains("create table public.purchases")
            .contains("create table public.followups")
            .contains("create table public.generation_records")
            .contains("create table public.guest_ownership_transfers")
            .contains("create table public.payment_webhook_events")
            .contains("create table public.free_reading_quota_events")
            .contains("create or replace function public.start_failed_reading_retry")
            .contains("alter table public.readings enable row level security")
            .doesNotContain("create table consent (");
    }

    @Test
    void v1UsesOneConsentRowPerSubjectAndBigintInternalSurrogateKeys()
        throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V1__"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("id bigint generated by default as identity primary key")
            .contains("terms_version text not null")
            .contains("privacy_version text not null")
            .contains("sensitive_data_version text not null")
            .contains("terms_accepted_at timestamptz not null")
            .contains("privacy_accepted_at timestamptz not null")
            .contains("sensitive_data_accepted_at timestamptz not null")
            .contains("create unique index consents_user_key")
            .contains("create unique index consents_guest_key")
            .contains("create table public.generation_records")
            .contains("id bigint generated by default as identity primary key")
            .doesNotContain("document_type public.consent_document_type not null")
            .doesNotContain("document_version text not null");
    }

    @Test
    void v1CanReplayLegacySupabaseSqlOnFreshPostgres() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V1__"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("create schema if not exists auth")
            .contains("create table if not exists auth.users")
            .contains("if to_regprocedure('auth.uid()') is null")
            .contains("create function auth.uid()")
            .contains("where rolname = 'anon'")
            .contains("where rolname = 'authenticated'")
            .contains("where rolname = 'service_role'");
    }

    @Test
    void v2MovesGuestReadingResultsIntoTemporaryCache() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V2__guest_reading_cache"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("create table if not exists public.guest_reading_cache")
            .contains("guest_cache_id uuid")
            .contains("create or replace function public.create_pending_guest_reading_cache")
            .contains("create or replace function public.complete_guest_reading_cache")
            .contains("create or replace function public.fail_guest_reading_cache")
            .contains("add constraint readings_user_owner_only")
            .contains("check (user_id is not null and guest_session_id is null)");
    }

    @Test
    void v7RetiresGuestReadingsAndVersionsAuthenticatedPayloads()
        throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString()
                .startsWith("V7__authenticated_reading_payload_schema"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("drop table if exists public.guest_reading_cache")
            .contains("drop table if exists public.guest_ownership_transfers")
            .contains("drop column if exists guest_session_id")
            .contains("alter table public.readings rename column input to input_payload")
            .contains("alter table public.readings rename column result to result_payload")
            .contains("alter table public.readings add column spread_type text")
            .contains("alter table public.readings add column schema_version integer")
            .contains("schema_version = 0")
            .contains("create or replace function public.create_pending_free_reading")
            .contains("requested_spread_type text")
            .contains("requested_schema_version integer")
			.contains("READING_GENERATION_IN_PROGRESS_OR_RETRY_REQUIRED")
			.contains("errcode = 'RL110'")
            .doesNotContain("create or replace function public.create_pending_guest_reading_cache");
    }

    @Test
    void v8RemovesPaymentTierAndQuotaContracts() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString()
                .startsWith("V8__remove_payment_and_reading_quota"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("drop table public.payment_webhook_events")
            .contains("drop table public.purchases")
            .contains("drop table public.free_reading_quota_events")
            .contains("drop type public.purchase_status")
            .contains("drop type public.reading_tier")
            .contains("drop column tier")
            .contains("create or replace function public.create_pending_reading")
            .contains("pg_advisory_xact_lock")
            .contains("'reading:' || requested_user_id::text || ':' || requested_request_id::text")
            .contains("create or replace function public.complete_reading_generation")
            .contains("create or replace function public.fail_reading_generation")
            .contains("'reading:' || inserted_reading.id::text")
            .contains("'reading-retry:' || owned_reading.id::text")
            .doesNotContain("create or replace function public.reserve_free_reading_quota")
            .doesNotContain("from public.reserve_free_reading_quota(")
            .doesNotContain("'free-reading:");
    }

    @Test
    void productionConfigurationNeverAutomaticallyBaselinesAnUnknownDatabase()
        throws IOException {
        var yaml = Files.readString(
            Path.of("src", "main", "resources", "application.yaml")
        );

        assertThat(yaml)
            .contains("ddl-auto: validate")
            .contains("baseline-on-migrate: false")
            .contains("validate-on-migrate: true")
            .doesNotContain("ip-hash-secret");
    }

    @Test
    void v9AddsDailyAndPaidCreditsWithoutAUsageLedger() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString()
                .startsWith("V9__daily_reading_credits"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("add column free_credit_balance")
            .contains("add column paid_credit_balance")
            .contains("add column free_credit_reset_date")
            .contains("add column credit_cost")
            .contains("readings_one_generating_per_user_uq")
            .contains("create or replace function public.get_reading_credit_status")
            .contains("create or replace function public.fail_stale_reading_generations")
            .contains("GENERATION_TIMEOUT")
            .contains("INSUFFICIENT_READING_CREDITS")
            .doesNotContain("create table public.reading_credit");
    }

}
