package com.myeongro.api.database;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class FlywayBaselineContractTests {

    private static final Path MIGRATION_DIRECTORY =
        Path.of("src", "main", "resources", "db", "migration");

    @Test
    void v1RecreatesTheCurrentSupabaseApplicationSchema() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V1__"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("create table public.profiles")
            .contains("create table public.readings")
            .contains("create table public.consents")
            .contains("create table public.purchases")
            .contains("create table public.followups")
            .contains("create table public.generation_records")
            .contains("create table public.guest_ownership_transfers")
            .contains("create table public.payment_webhook_events")
            .contains("create table public.free_reading_quota_events")
            .contains("create or replace function public.start_failed_reading_retry")
            .contains("alter table public.readings enable row level security")
            .doesNotContain("create table consent (");
    }

    @Test
    void v1UsesOneConsentRowPerSubjectAndBigintInternalSurrogateKeys()
        throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V1__"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("id bigint generated by default as identity primary key")
            .contains("terms_version text not null")
            .contains("privacy_version text not null")
            .contains("sensitive_data_version text not null")
            .contains("terms_accepted_at timestamptz not null")
            .contains("privacy_accepted_at timestamptz not null")
            .contains("sensitive_data_accepted_at timestamptz not null")
            .contains("create unique index consents_user_key")
            .contains("create unique index consents_guest_key")
            .contains("create table public.generation_records")
            .contains("id bigint generated by default as identity primary key")
            .doesNotContain("document_type public.consent_document_type not null")
            .doesNotContain("document_version text not null");
    }

    @Test
    void v1CanReplayLegacySupabaseSqlOnFreshPostgres() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V1__"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("create schema if not exists auth")
            .contains("create table if not exists auth.users")
            .contains("if to_regprocedure('auth.uid()') is null")
            .contains("create function auth.uid()")
            .contains("where rolname = 'anon'")
            .contains("where rolname = 'authenticated'")
            .contains("where rolname = 'service_role'");
    }

    @Test
    void v2MovesGuestReadingResultsIntoTemporaryCache() throws IOException {
        var migration = Files.list(MIGRATION_DIRECTORY)
            .filter(path -> path.getFileName().toString().startsWith("V2__guest_reading_cache"))
            .findFirst()
            .orElseThrow();

        var sql = Files.readString(migration);

        assertThat(sql)
            .contains("create table if not exists public.guest_reading_cache")
            .contains("guest_cache_id uuid")
            .contains("create or replace function public.create_pending_guest_reading_cache")
            .contains("create or replace function public.complete_guest_reading_cache")
            .contains("create or replace function public.fail_guest_reading_cache")
            .contains("add constraint readings_user_owner_only")
            .contains("check (user_id is not null and guest_session_id is null)");
    }

    @Test
    void productionConfigurationNeverAutomaticallyBaselinesAnUnknownDatabase()
        throws IOException {
        var yaml = Files.readString(
            Path.of("src", "main", "resources", "application.yaml")
        );

        assertThat(yaml)
            .contains("ddl-auto: validate")
            .contains("baseline-on-migrate: false")
            .contains("validate-on-migrate: true");
    }

    @Test
    void migrationPolicyDocumentsResetRequirementForRewrittenBaseline()
        throws IOException {
        var policy = Files.readString(
            Path.of("src", "main", "resources", "db", "migration", "README.md")
        );

        assertThat(policy)
            .contains("intentionally rewrites the cumulative V1/V3 baseline")
            .contains("validate-on-migrate=true")
            .contains("clean-disabled=true")
            .contains("old V1 or V3 checksum")
            .contains("reset affected non-production databases")
            .contains("do not edit an already-applied migration");
    }

    @Test
    void migrationPolicyDocumentsFreshPostgresReplayCheck()
        throws IOException {
        var policy = Files.readString(
            Path.of("src", "main", "resources", "db", "migration", "README.md")
        );

        assertThat(policy)
            .contains("Fresh Docker Postgres replay check")
            .contains("myeongro-flyway-check-postgres")
            .contains("docker run")
            .contains("POSTGRES_PORT=55432")
            .contains("spring.flyway.clean-disabled=false")
            .contains("flyway_schema_history");
    }
}
