create schema if not exists public;

create table public.profiles (
  id uuid primary key,
  display_name varchar(255),
  deleted_at timestamp with time zone,
  purge_after timestamp with time zone,
  purged_at timestamp with time zone,
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp
);

create table public.oauth_accounts (
  id bigint generated by default as identity primary key,
  profile_id uuid not null,
  provider varchar(64) not null,
  provider_user_id varchar(255) not null,
  email varchar(255),
  display_name varchar(255),
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp,
  unique (provider, provider_user_id),
  foreign key (profile_id) references public.profiles(id) on delete cascade
);

create table public.readings (
  id uuid primary key,
  user_id uuid not null,
  deleted_at timestamp with time zone,
  foreign key (user_id) references public.profiles(id) on delete cascade
);
