create schema if not exists public;

create table public.readings (
  id uuid primary key,
  user_id uuid not null,
  kind varchar(16) not null,
  status varchar(16) not null,
  title varchar(255) not null,
  input varchar(4000) not null,
  result varchar(4000),
  deleted_at timestamp,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table public.generation_records (
  id bigint generated by default as identity primary key,
  reading_id uuid not null,
  error_code varchar(128),
  created_at timestamp not null
);
