-- Replace the fixed three-column consent snapshot with append-only, versioned
-- events so each document can be accepted and withdrawn independently.

create table public.consent_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  document_type varchar(64) not null check (document_type in (
    'TERMS',
    'PRIVACY',
    'SENSITIVE_DATA',
    'AI_OVERSEAS_TRANSFER',
    'SAJU_INPUT'
  )),
  document_version text not null check (length(trim(document_version)) > 0),
  action varchar(16) not null check (action in ('ACCEPTED', 'WITHDRAWN')),
  occurred_at timestamptz not null,
  method varchar(64) not null check (length(trim(method)) > 0),
  created_at timestamptz not null default now()
);

create index consent_events_user_document_latest_idx
  on public.consent_events (user_id, document_type, occurred_at desc, id desc);

insert into public.consent_events (
  user_id, document_type, document_version, action, occurred_at, method
)
select user_id, 'TERMS', terms_version, 'ACCEPTED', terms_accepted_at, 'legacy-migration'
from public.consents
union all
select user_id, 'PRIVACY', privacy_version, 'ACCEPTED', privacy_accepted_at, 'legacy-migration'
from public.consents
union all
select user_id, 'SENSITIVE_DATA', sensitive_data_version, 'ACCEPTED', sensitive_data_accepted_at, 'legacy-migration'
from public.consents;

comment on table public.consents is
  'Legacy consent snapshot retained for rollback; new writes use consent_events.';
