-- Store only the account-level statement that the user is at least 19.
-- Exact birth dates and identity-verification data are intentionally not collected.

create table public.adult_eligibility_assertions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  policy_version text not null check (length(trim(policy_version)) > 0),
  confirmed_at timestamptz not null,
  method varchar(64) not null check (length(trim(method)) > 0),
  created_at timestamptz not null default now(),
  unique (user_id, policy_version)
);

create index adult_eligibility_assertions_user_confirmed_idx
  on public.adult_eligibility_assertions (user_id, confirmed_at desc, id desc);
